targets:
  $default:
    builders:
      graphql_codegen:
        enabled: true
        options:
          clients:
            - graphql_flutter
          schema: lib/graphql/schema.graphql
          queries_glob: lib/graphql/**/*.graphql
          output_directory: lib/graphql
          scalar_mapping:
            - graphql_type: DateTime
              dart_type: DateTime
